name: tox
on:  # yamllint disable-line rule:truthy
  - pull_request
jobs:
  python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pyver: ['2.7', '3.6', '3.7', '3.8', '3.9']
    steps:
      - name: checkout PR
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.pyver }}
      - name: Install platform dependencies, python, tox
        run: |
          set -euxo pipefail
          python -m pip install --upgrade pip
          pip install -rtox_requirements.txt
      - name: Run tox tests
        run: |
          set -euxo pipefail
          tox
        env:
          COVERALLS_CMD: coveralls
          COVERALLS_PARALLEL: "true"
  python-26:
    runs-on: ubuntu-16.04
    steps:
      - name: checkout PR
        uses: actions/checkout@v2
      - name: Install python, dependencies
        run: |
          set -euo pipefail
          curl -sSf --retry 5 -o python-2.6.tar.bz2 ${PY26URL}
          sudo tar xjf python-2.6.tar.bz2 --directory /
          myuid=$(id -u)
          mygid=$(id -g)
          sudo chown -R $myuid:$mygid /home/travis/virtualenv
          source /home/travis/virtualenv/python2.6/bin/activate
          set -x
          pip install -rtox_requirements.txt
        env:
          # yamllint disable-line rule:line-length
          PY26URL: https://storage.googleapis.com/travis-ci-language-archives/python/binaries/ubuntu/14.04/x86_64/python-2.6.tar.bz2
          VIRTUAL_ENV_DISABLE_PROMPT: "true"
      - name: Run tox tests
        run: |
          set -euo pipefail
          source /home/travis/virtualenv/python2.6/bin/activate
          set -x
          tox -e py26-tox20
        env:
          COVERALLS_CMD: "echo skipping coveralls"
          SAFETY_CMD: "echo skipping safety"
          VIRTUAL_ENV_DISABLE_PROMPT: "true"
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
